#!/bin/bash

# ==============================================================================
# Script: setup_private_dhcp_native.sh
# Description: Native ISC DHCP Server Setup with Progress Tracking
# Copyright: © b1swa
# Contact: sandipbiswa10@gmail.com
# ==============================================================================

# Exit on error
set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

# Check for whiptail
if ! command -v whiptail &> /dev/null; then
    echo "Error: whiptail is required."
    exit 1
fi

# Check for root
if [ "$EUID" -ne 0 ]; then
    echo "Please run with sudo."
    exit 1
fi

# 1. Branding
show_branding() {
    local HOSTNAME=$(hostname)
    local HOST_IP=$(hostname -I | awk '{print $1}')
    whiptail --title "Native Private DHCP (ISC)" --msgbox "Welcome to the Native Private DHCP Setup Tool\n\n[ System Information ]\nHostname: $HOSTNAME\nHost IP: $HOST_IP\n\nEngine: ISC DHCP Server\nCopyright © b1swa\nContact: sandipbiswa10@gmail.com" 16 65
}
show_branding

# 2. Get Inputs
DEFAULT_IFACE=$(ip -o -4 route show to default | awk '{print $5}' | head -n1)
[ -z "$DEFAULT_IFACE" ] && DEFAULT_IFACE=$(ip -o link show | awk -F': ' '{print $2}' | grep -v "lo" | head -n1)

INTERFACE=$(whiptail --title "Interface" --inputbox "Enter the network interface to listen on:" 10 60 "$DEFAULT_IFACE" 3>&1 1>&2 2>&3)

# Suggest Subnet/Mask based on current IP
CURRENT_IP=$(ip -o -4 addr show dev "$INTERFACE" | awk '{print $4}' | head -n1)
IP_PART=$(echo $CURRENT_IP | cut -d/ -f1)
SUBNET_SUGGEST=$(echo $IP_PART | cut -d. -f1-3).0

SUBNET=$(whiptail --title "Subnet" --inputbox "Enter the subnet address:" 10 60 "$SUBNET_SUGGEST" 3>&1 1>&2 2>&3)
NETMASK=$(whiptail --title "Netmask" --inputbox "Enter the netmask:" 10 60 "255.255.255.0" 3>&1 1>&2 2>&3)

RANGE_START=$(whiptail --title "IP Range Start" --inputbox "Enter the start of the DHCP range:" 10 60 "$(echo $SUBNET | cut -d. -f1-3).100" 3>&1 1>&2 2>&3)
RANGE_END=$(whiptail --title "IP Range End" --inputbox "Enter the end of the DHCP range:" 10 60 "$(echo $SUBNET | cut -d. -f1-3).200" 3>&1 1>&2 2>&3)

ROUTERS=$(whiptail --title "Default Gateway" --inputbox "Enter the default gateway (Routers):" 10 60 "$IP_PART" 3>&1 1>&2 2>&3)
DNS_SERVERS=$(whiptail --title "DNS Servers" --inputbox "Enter DNS servers (comma separated):" 10 60 "$IP_PART, 8.8.8.8" 3>&1 1>&2 2>&3)
DOMAIN=$(whiptail --title "Domain Name" --inputbox "Enter the domain name (optional):" 10 60 "b1swa.local" 3>&1 1>&2 2>&3)

# --- Execution with Progress Gauge ---

{
    echo 10; sleep 1
    echo "XXX"
    echo "📦 Phase 1: Installing ISC DHCP Server..."
    echo "XXX"
    apt-get update -y > /dev/null
    apt-get install -y isc-dhcp-server isc-dhcp-client > /dev/null
    
    echo 30; sleep 1
    echo "XXX"
    echo "🔧 Phase 2: Configuring Interface..."
    echo "XXX"
    # Update /etc/default/isc-dhcp-server
    sed -i "s/^INTERFACESv4=.*/INTERFACESv4=\"$INTERFACE\"/" /etc/default/isc-dhcp-server
    
    echo 50; sleep 1
    echo "XXX"
    echo "📝 Phase 3: Generating dhcpd.conf..."
    echo "XXX"
    
    # Backup existing config
    cp /etc/dhcp/dhcpd.conf /etc/dhcp/dhcpd.conf.bak.$(date +%F_%T)
    
    cat <<EOF > /etc/dhcp/dhcpd.conf
# ==============================================================================
# DHCP Server Configuration
# Generated by setup_private_dhcp_native.sh
# Copyright © b1swa
# ==============================================================================

option domain-name "$DOMAIN";
option domain-name-servers $DNS_SERVERS;

default-lease-time 600;
max-lease-time 7200;

# Use this to enable/disable authoritative
authoritative;

# Subnet declaration
subnet $SUBNET netmask $NETMASK {
  range $RANGE_START $RANGE_END;
  option routers $ROUTERS;
  option subnet-mask $NETMASK;
  option broadcast-address $(echo $SUBNET | cut -d. -f1-3).255;
}
EOF

    echo 80; sleep 1
    echo "XXX"
    echo "🔥 Phase 4: Configuring Firewall (UFW)..."
    echo "XXX"
    if command -v ufw &> /dev/null && ufw status | grep -q "active"; then
        # Allow both UDP and TCP for DHCP ports (67 & 68)
        ufw allow 67/udp > /dev/null
        ufw allow 68/udp > /dev/null
        ufw allow 67/tcp > /dev/null
        ufw allow 68/tcp > /dev/null
    fi

    echo 90; sleep 1
    echo "XXX"
    echo "🚀 Phase 5: Starting DHCP Service..."
    echo "XXX"
    # Check syntax
    dhcpd -t -cf /etc/dhcp/dhcpd.conf > /dev/null 2>&1
    
    systemctl restart isc-dhcp-server
    systemctl enable isc-dhcp-server

    echo 100; sleep 1
} | whiptail --title "Installation Progress" --gauge "Preparing to install..." 10 60 0

# Final Message
whiptail --title "Success!" --msgbox "ISC DHCP Server is now LIVE!\n\nInterface: $INTERFACE\nSubnet: $SUBNET\nRange: $RANGE_START - $RANGE_END\nGateway: $ROUTERS\n\n[ Status ]\n- Engine: ISC DHCP Server\n- Firewall: DHCP Ports (67, 68) UDP/TCP allowed\n\n[ Client Tip ]\nTo request an IP on client machines, use:\nsudo apt install isc-dhcp-client\nsudo dhclient <interface>\n\nCopyright © b1swa\nContact: sandipbiswa10@gmail.com" 22 70

echo -e "${GREEN}✅ Done! DHCP server is configured on $INTERFACE.${NC}"
echo -e "${GREEN}Check status with: systemctl status isc-dhcp-server${NC}"
echo -e "${GREEN}Client test command: sudo dhclient -v <interface>${NC}"
